package com.CSCI152.team4.server.Accounts.Settings;

public enum Permissions {
    REPORT_CREATE,
    REPORT_EDIT,
    REPORT_DELETE,
    UPDATE_CREATE,
    UPDATE_EDIT,
    UPDATE_DELETE,
    ATTACHMENTS_CREATE,
    ATTACHMENTS_DELETE,
    IMAGES_CREATE,
    IMAGES_EDIT,
    PROFILES_CREATE,
    PROFILES_EDIT,
    PROFILES_DELETE,
    NOTIFICATIONS_EDIT,
    ACCOUNTS_REGISTER,
    ACCOUNTS_PROMOTE,
    ACCOUNTS_DEMOTE,
    ACCOUNTS_VIEW,
    ACCOUNTS_UPDATE,
    PERMISSIONS_EDIT
}
